### ISSUE TITLE
Logic isn't Working

### ISSUE THREAD

**Issue by AnshSharma03** [AnshSharma03/Tic-Tac-Toe#1]
The logic is not working. See to the logic once.

**Comment by irishpines** [comment]
I've fixed the code so it's working reliably. If you can assign me as a collaborator I can upload a commit and create a pull request for you to review?

**Comment by renato04** [comment]
@irishpines I think you can fork the project and open a PR from your forked repository to this project.

**Comment by irishpines** [comment]
Thanks @renato04, I'll do that.

**Comment by AnuragParashar2000** [comment]
I have added the appropriate changes,
